### ISSUE TITLE
Quoted-printable encoding unrecognized on GitHub

### ISSUE THREAD

**Issue by pchaigno** [mariozaizar/language-eml#15]
### Prerequisites

*I haven't reproduced the issue in Atom. Please see the description.*
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked that your issue isn't already filed: https://github.com/mariozaizar/language-eml/issues

### Description

We're considering (cf. github/linguist#4201) using this EML grammar to highlight all `.eml` and `.mbox` files on GitHub and GitLab. Unfortunately, the grammar's output has some errors (see [Lightshow example](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fmariozaizar%2Flanguage-eml%2Fblob%2Fmaster%2Fgrammars%2Flanguage-eml.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fmariozaizar%2Flanguage-eml%2Fblob%2F894a2697e04b0448c0d92e9c346586e193bcedf0%2Fspec%2Ffixtures%2Fwindows-1251.eml&code=)) for [quoted-printable encoding](https://stackoverflow.com/a/4016098/6884590) (if that's not obvious, I don't know much about EML).

I haven't tested under Atom yet, so it's possible the issue is only with GitHub's interpreter for grammars. GitHub uses a PCRE-based regular expression engine, which has a few differences in interpretation. I had a quick look at the grammar and did not spotted any though.

### Steps to Reproduce

1. Try to highlight a EML file containing quoted-printable encoding [with Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fmariozaizar%2Flanguage-eml%2Fblob%2Fmaster%2Fgrammars%2Flanguage-eml.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fmariozaizar%2Flanguage-eml%2Fblob%2F894a2697e04b0448c0d92e9c346586e193bcedf0%2Fspec%2Ffixtures%2Fwindows-1251.eml&code=).

**Expected behavior:** Characters following the quoted-printable marker (`=3D`) to be highlighted correctly.

**Actual behavior:** Characters following the quoted-printable marker are highlighted with a red background.

**Reproduces how often:** 100%

### Versions

The highlighting bug happens with commit c9f354e of the present grammar.

### Additional Information

Lightshow is a simple interface to test the highlighter used on GitHub.com. It simply takes the grammar provided and interprets it on the given example.

**Comment by pchaigno** [comment]
@mariozaizar Did you get a chance to look into this?

**Comment by mariozaizar** [comment]
@pchaigno I'm sorry, somehow I'm didn't got this notification until now. Let me take a closer look in the next couple days. Thanks for reporting it 🙏

**Comment by wesinator** [comment]
`=3D` text looks normal in Atom; the 2 color code values are still highlighted red by the inherited HTML highlighting. https://github.com/mariozaizar/language-eml/blob/894a2697e04b0448c0d92e9c346586e193bcedf0/spec/fixtures/windows-1251.eml#L81

**Comment by pchaigno** [comment]
> `=3D` text looks normal in Atom; the 2 color code values are still highlighted red by the inherited HTML highlighting.

@wesinator So the highlighting is the same as with [Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fmariozaizar%2Flanguage-eml%2Fblob%2Fmaster%2Fgrammars%2Flanguage-eml.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fmariozaizar%2Flanguage-eml%2Fblob%2F894a2697e04b0448c0d92e9c346586e193bcedf0%2Fspec%2Ffixtures%2Fwindows-1251.eml&code=)? Could you post a screenshot of the result?

**Comment by wesinator** [comment]
@pchaigno No, Atom has the expected behaviour. https://github.com/mariozaizar/language-eml/blob/894a2697e04b0448c0d92e9c346586e193bcedf0/spec/fixtures/windows-1251.eml#L38 is not highlighted red.

![image](https://user-images.githubusercontent.com/5124946/45964629-54c62f80-bff4-11e8-8c51-3fa5ba579389.png)

**Comment by pchaigno** [comment]
@wesinator Ah, I see. Thanks!

@Alhadis Looks like there is a discrepancy between the interpretations GitHub and Atom are having for this grammar. I couldn't find any non-PCRE-compliant regular expressions, but maybe you will...?

**Comment by Alhadis** [comment]
The expressions aren't the problem. [This is](https://github.com/mariozaizar/language-eml/blob/c9f354e6b33b4d4de73668be4660e6519a32e51d/grammars/language-eml.cson#L98):

~~~cson
# Content-Type: text/html;
{
	'match': '^(?i)<html>(.|\s)*<\/html>$',
	'include': 'text.html.basic'
},
~~~

We're still using the [old TextMate grammar](https://github.com/textmate/html.tmbundle) for HTML highlighting, which is the likely culprit. Ergo, we have two choices:

1. Submit a fix upstream
2. Switch to Atom's grammar for HTML highlighting (recommended)

**Comment by Alhadis** [comment]
FYI, this grammar has numerous mistakes (several patterns are incorrectly escaped, and the HTML pattern mentioned above is ignoring the `match` key because the `include` rule takes precedence. The intended entry should have been:

~~~diff
 # Content-Type: text/html;
 {
 	'match': '^(?i)<html>(.|\s)*<\/html>$',
-	'include': 'text.html.basic'
+	'captures':
+		'0':
+			'patterns': [
+				{
+					'include': 'text.html.basic'
+				}
+			]
+	}
 },
~~~

Or much more succinctly:

~~~diff
 # Content-Type: text/html;
 {
 	'match': '^(?i)<html>(.|\s)*<\/html>$',
-	'include': 'text.html.basic'
+	'captures':
+		'0': 'patterns': ['include': 'text.html.basic']
 },
~~~

But this alone is inadequate, because:
1. TextMate patterns are restricted to matching one line at a time, so `<html>(.|\s)</html>` will only match lines which start with `<html>` and end in `</html>`. Multiline markup isn't matched.
2. An opening `<html>` tag with attributes will fail to match, as in the examples.

The only reason there even *is* HTML highlighting is because of the incorrect `captures` key (explained above). Which is also the reason HTML highlighting appears outside of a pair of `<html>` tags.

I'll send a pull-request.

**Comment by mariozaizar** [comment]
Sorry folks, I'm quite disconnected from work and opensource for the last weeks due to an imminent baby arrival 🍼 ; but if you guys want to open PRs against this addressable comments I'm more than happy to review and merge to keep things moving. Thanks again!

**Comment by mariozaizar** [comment]
💡I just published John's fixes #16 as [v1.1.1](https://github.com/mariozaizar/language-eml/commits/9834b9cdc95b8b010897f5954c8e74a9017ab39d/).

Unfortunately, I'm still seeing the red background on Lightshow using the [new version](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fmariozaizar%2Flanguage-eml%2Fblob%2F9834b9cdc95b8b010897f5954c8e74a9017ab39d%2Fgrammars%2Flanguage-eml.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fmariozaizar%2Flanguage-eml%2Fblob%2F9834b9cdc95b8b010897f5954c8e74a9017ab39d%2Fspec%2Ffixtures%2Fwindows-1251.eml&code=) in the same way as the [old version](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fmariozaizar%2Flanguage-eml%2Fblob%2Fc9f354e6b33b4d4de73668be4660e6519a32e51d%2Fgrammars%2Flanguage-eml.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fmariozaizar%2Flanguage-eml%2Fblob%2Fc9f354e6b33b4d4de73668be4660e6519a32e51d%2Fspec%2Ffixtures%2Fwindows-1251.eml&code=), but as Ԝеѕ pointed out, Atom doesn't show any red background 🤔 

![bug](https://user-images.githubusercontent.com/164819/45992914-fd9a7c00-c040-11e8-9b9c-34f1878b90c5.png)

**Comment by Alhadis** [comment]
Aye, that's because it's loading the [old TextMate grammar](https://github.com/textmate/html.tmbundle), which is applying the highlighting. I'm literally in the middle of prepping a PR to get it replaced on Linguist's side.

Once merged, changes will become visible across the site when the next release of Linguist has been cut.

**Comment by pchaigno** [comment]
Closing this as it's an issue with the HTML grammar. Thanks a lot @Alhadis!

@mariozaizar Once the fix is in place at Linguist, we're likely to use this grammar to highlight all `.eml` and `.mbox` files on GitHub.com (cf. github/linguist#4201).
